markdown: kramdown

url: https://davedavenport.github.io/rofi
name: Rofi
logo: images/rofi-large.png
description: A window switcher, run dialog and dmenu replacement
github-url: https://github.com/DaveDavenport/rofi
github-user-url: https://github.com/DaveDavenport/
github-user: Dave Davenport
github-version-stable: 1.3.1
