markdown: kramdown

url: https://comfoxx.github.io/rofi-old-generator
name: Rofi Archive
logo: images/rofi-large.png
description: A window switcher, run dialog and dmenu replacement
github-url: https://github.com/DaveDavenport/rofi
github-user-url: https://github.com/DaveDavenport/
github-user: Dave Davenport
github-version-stable: 1.5.0
